/**
 * Pins the history wording (`src/editor/event-label.ts`) — every event of the
 * log rendered as one business-worded line, in both languages, and the
 * totality promise: no variant, known or rogue, may break the history screen.
 */
import { describe, expect, it } from 'vitest'
import { eventLabel } from '../../src/editor/event-label'
import { hasLabel } from '../../src/i18n'
import { PARSE_ERROR_CODES } from '@project-review/core/services/parse'
import type { DomainEvent } from '@project-review/core/events'
import { otherPortfolio, testPortfolio } from '../../../core/tests/fixtures/hand-built-portfolios'
import { ONE_EVENT_PER_VARIANT } from '../fixtures/one-event-per-variant'
import { categoryId } from '@project-review/core/values/ids'
import { isoDate } from '@project-review/core/values/date'
import { progressOf } from '@project-review/core/values/progress'

const NBSP = ' '

describe('eventLabel — composed wording (no catalog entry for the pair)', () => {
  it('names both navigation modes in the history language', () => {
    const event: DomainEvent = {
      type: 'SettingChanged',
      setting: 'navigation',
      before: 'sections',
      after: 'linear',
    }
    expect(eventLabel(event, 'fr')).toContain('Par sections ▸ Linéaire')
    expect(eventLabel(event, 'en')).toContain('By section ▸ Linear')
  })
  const healthChange: DomainEvent = {
    type: 'ProjectFieldChanged',
    id: 'P-04',
    field: 'health',
    before: 'watch',
    after: 'alert',
  }

  it('composes subject · field : before ▸ after from the core catalog value labels (fr)', () => {
    expect(eventLabel(healthChange, 'fr')).toBe(`P-04 · Santé${NBSP}: Vigilance ▸ Alerte`)
  })

  it('uses the project name when the current portfolio can resolve its identity', () => {
    expect(
      eventLabel(healthChange, 'fr', (kind) =>
        kind === 'project' ? 'Infrastructure réseau' : undefined,
      ),
    ).toContain('Infrastructure réseau · Santé')
  })

  it('translates field AND values, and drops the French colon space (en)', () => {
    expect(eventLabel(healthChange, 'en')).toBe('P-04 · Health: Watch ▸ Alert')
  })

  it('formats a percentage with its non-breaking space', () => {
    const changed: DomainEvent = {
      type: 'ProjectFieldChanged',
      id: 'P-09',
      field: 'progress',
      before: progressOf(65)!,
      after: progressOf(70)!,
    }
    expect(eventLabel(changed, 'fr')).toBe(`P-09 · Avancement${NBSP}: 65${NBSP}% ▸ 70${NBSP}%`)
  })

  it('names the missing value rather than printing "undefined"', () => {
    const cleared: DomainEvent = {
      type: 'ProjectFieldChanged',
      id: 'P-02',
      field: 'lead',
      before: 'Camille NOËL',
      after: undefined,
    }
    expect(eventLabel(cleared, 'fr')).toBe(`P-02 · Porteur${NBSP}: Camille NOËL ▸ (vide)`)
    expect(eventLabel(cleared, 'en')).toBe('P-02 · Lead: Camille NOËL ▸ (empty)')
  })

  it('shortens a free-text value beyond 40 characters — the history stays one line', () => {
    const long = 'Un porteur au patronyme démesurément long pour une ligne d’historique'
    const cleared: DomainEvent = {
      type: 'ProjectFieldChanged',
      id: 'P-02',
      field: 'lead',
      before: undefined,
      after: long,
    }
    const label = eventLabel(cleared, 'fr')
    expect(label).toContain(`${long.slice(0, 39)}…`)
    expect(label).not.toContain(long)
  })

  it('shows an ISO date in its short display form', () => {
    const date: DomainEvent = {
      type: 'ReviewFieldChanged',
      field: 'reviewDate',
      before: isoDate('2026-07-02')!,
      after: isoDate('2026-09-03')!,
    }
    expect(eventLabel(date, 'fr')).toBe(`Revue · Date de revue${NBSP}: 02/07/26 ▸ 03/09/26`)
  })
})

describe('eventLabel — wording generated BY the catalog', () => {
  it('states an import as a replacement, with its project count correctly pluralised', () => {
    const imported: DomainEvent = {
      type: 'PortfolioReplaced',
      before: testPortfolio(),
      after: otherPortfolio(),
    }
    expect(eventLabel(imported, 'fr')).toBe('Import du portefeuille — remplacement (1 projet(s))')
    expect(eventLabel(imported, 'en')).toBe('Portfolio import — replacement (1 project(s))')
  })

  it('states a merge with the figures derived from the event itself', () => {
    // 1 replaced (in `before`), 1 added (in `after` only) — the label must
    // agree with the import preview, both reading `mergeReport`.
    const merged: DomainEvent = {
      type: 'ProjectsMerged',
      before: { projects: [{ value: testPortfolio().projects[1]!, index: 1 }], categories: [] },
      after: {
        projects: [
          { value: testPortfolio().projects[1]!, index: 1 },
          { value: testPortfolio().projects[0]!, index: 2 },
        ],
        categories: [],
      },
    }
    expect(eventLabel(merged, 'fr')).toBe('Fusion — 1 projet(s) remplacé(s), 1 ajouté(s)')
    expect(eventLabel(merged, 'en')).toBe('Merge — 1 project(s) replaced, 1 added')
  })

  it('reads a decision list change as an addition, not as a diff', () => {
    const added: DomainEvent = {
      type: 'ProjectDecisionsChanged',
      id: 'P-18',
      before: [],
      after: [{ question: 'Arbitrer le lot 2 ?' }],
    }
    expect(eventLabel(added, 'fr')).toBe('P-18 · décision ajoutée')
    expect(eventLabel(added, 'en')).toBe('P-18 · decision added')
  })

  it('separates a resized list from a rewritten one', () => {
    const grown: DomainEvent = {
      type: 'ProjectListChanged',
      id: 'P-04',
      list: 'done',
      before: ['a'],
      after: ['a', 'b'],
    }
    expect(eventLabel(grown, 'fr')).toBe(
      `P-04 · Réalisé depuis la dernière revue${NBSP}: 1 puce(s) ▸ 2`,
    )

    const rewritten: DomainEvent = { ...grown, before: ['a', 'b'], after: ['a', 'c'] }
    expect(eventLabel(rewritten, 'fr')).toBe('P-04 · Réalisé depuis la dernière revue réécrit')
    expect(eventLabel(rewritten, 'en')).toBe('P-04 · Done since last review rewritten')
  })

  it('quotes a created category with French guillemets in fr, plain quotes in en', () => {
    const created: DomainEvent = {
      type: 'CategoryCreated',
      category: { id: categoryId('reseau')!, name: 'Réseau', color: 'blue' },
      index: 2,
    }
    expect(eventLabel(created, 'fr')).toBe(`Catégorie «${NBSP}Réseau${NBSP}» créée`)
    expect(eventLabel(created, 'en')).toBe('Category "Réseau" created')
  })

  it('reads a settings toggle through the core catalog stage/level vocabulary', () => {
    const stage: DomainEvent = {
      type: 'ProjectFieldChanged',
      id: 'P-19',
      field: 'stage',
      before: 'toScope',
      after: 'ready',
    }
    expect(eventLabel(stage, 'fr')).toBe(`P-19 · Étape${NBSP}: À cadrer ▸ Prêt`)
    expect(eventLabel(stage, 'en')).toBe('P-19 · Stage: To scope ▸ Ready')
  })

  it('renders a boolean setting as yes / no', () => {
    const toggled: DomainEvent = {
      type: 'SettingChanged',
      setting: 'archives',
      before: true,
      after: false,
    }
    expect(eventLabel(toggled, 'fr')).toBe(`Paramètres · Archives${NBSP}: oui ▸ non`)
    expect(eventLabel(toggled, 'en')).toBe('Settings · Archives: yes ▸ no')
  })

  it('speaks the catalog for palette, theme style and language values', () => {
    const palette: DomainEvent = {
      type: 'SettingChanged',
      setting: 'palette',
      before: 'tailwind',
      after: 'material',
    }
    expect(eventLabel(palette, 'fr')).toBe(`Paramètres · Palette${NBSP}: Tailwind ▸ Material`)

    const style: DomainEvent = {
      type: 'SettingChanged',
      setting: 'style',
      before: 'flat',
      after: 'institutional',
    }
    expect(eventLabel(style, 'en')).toBe('Settings · Theme: Flat ▸ Institutional')

    const language: DomainEvent = {
      type: 'SettingChanged',
      setting: 'language',
      before: 'fr',
      after: 'en',
    }
    expect(eventLabel(language, 'fr')).toBe(`Paramètres · Langue${NBSP}: FR ▸ EN`)
  })

  it('names a logo change as an image — never the bytes of the data URI', () => {
    const logo: DomainEvent = {
      type: 'IdentityFieldChanged',
      field: 'logo',
      before: undefined,
      after: 'data:image/png;base64,AAAA',
    }
    expect(eventLabel(logo, 'fr')).toBe(`Identité · Logo${NBSP}: (vide) ▸ image`)
    expect(eventLabel(logo, 'en')).toBe('Identity · Logo: (empty) ▸ image')
  })

  it('counts embedded faces — never the bytes of their data URIs', () => {
    const face = {
      family: 'Atelier',
      weight: '400',
      style: 'normal',
      dataUri: 'data:font/woff2;base64,d09GMg==',
    } as const
    const embedded: DomainEvent = {
      type: 'SettingChanged',
      setting: 'fontFaces',
      before: undefined,
      after: [face, { ...face, weight: '700 800' }],
    }
    expect(eventLabel(embedded, 'fr')).toBe(
      `Paramètres · Police embarquée${NBSP}: (vide) ▸ 2 fonte(s)`,
    )
    expect(eventLabel(embedded, 'en')).toBe('Settings · Embedded font: (empty) ▸ 2 face(s)')
  })

  it('names the portfolio palette — never its twelve hex values', () => {
    const colors = {
      blue: '#3460d8',
      indigo: '#7a4ecf',
      teal: '#017661',
      cyan: '#016770',
      green: '#027a1f',
      olive: '#666f02',
      amber: '#7e5e01',
      orange: '#a35301',
      red: '#c52b30',
      purple: '#a43cab',
      brown: '#7d4e2c',
      taupe: '#6b6456',
    } as const
    const labelled: DomainEvent = {
      type: 'SettingChanged',
      setting: 'customPalette',
      before: undefined,
      after: { label: 'Couleurs maison', colors },
    }
    expect(eventLabel(labelled, 'fr')).toBe(
      `Paramètres · Palette du portefeuille${NBSP}: (vide) ▸ Couleurs maison`,
    )
    // No label of its own: the history counts, exactly as it does for faces.
    const bare: DomainEvent = {
      type: 'SettingChanged',
      setting: 'customPalette',
      before: { colors },
      after: undefined,
    }
    expect(eventLabel(bare, 'en')).toBe('Settings · Portfolio palette: 12 colours ▸ (empty)')
  })
})

describe('eventLabel — empty free-slide title stays readable', () => {
  it('shows the display dash, never empty quotes', () => {
    const created = ONE_EVENT_PER_VARIANT.find(
      (e): e is Extract<DomainEvent, { type: 'FreeSlideCreated' }> => e.type === 'FreeSlideCreated',
    )!
    const empty: DomainEvent = { ...created, slide: { ...created.slide, title: '' } }
    expect(eventLabel(empty, 'en')).toBe('Free slide "—" added')
    expect(eventLabel(empty, 'fr')).toBe(`Slide libre «${NBSP}—${NBSP}» ajoutée`)
  })
})

describe('eventLabel — totality', () => {
  it('never returns an empty label, for any variant of the union', () => {
    for (const event of ONE_EVENT_PER_VARIANT) {
      for (const language of ['fr', 'en'] as const) {
        const label = eventLabel(event, language)
        expect(label.length).toBeGreaterThan(0)
        // A raw key leaking through would read like `editor.event.…`.
        expect(label.startsWith('editor.')).toBe(false)
      }
    }
  })

  it('keeps the runtime promise on an event outside the union: key shown, never a throw', () => {
    // The cast bypasses the type on purpose: totality is a RUNTIME promise
    // (the history must never be the thing that breaks).
    const rogue = { type: 'SomethingNew' } as unknown as DomainEvent
    expect(eventLabel(rogue, 'fr')).toBe('editor.event.SomethingNew')
  })

  it('hasLabel sees both catalogs, and nothing else', () => {
    expect(hasLabel('editor.nav.portfolio')).toBe(true) // editor catalog
    expect(hasLabel('stage.ready')).toBe(true) // core catalog
    expect(hasLabel('editor.event.SomethingNew')).toBe(false)
    expect(hasLabel('__proto__')).toBe(false)
  })
})

describe('parse errors — editor catalog coverage', () => {
  it('every parse error code resolves to an editor.error.* entry', () => {
    for (const code of PARSE_ERROR_CODES) {
      expect(hasLabel(`editor.error.${code}`), code).toBe(true)
    }
  })

  it('the two pre-parse refusals resolve too', () => {
    expect(hasLabel('editor.error.badJson')).toBe(true)
    expect(hasLabel('editor.error.tooLarge')).toBe(true)
  })
})
