<script module lang="ts">
  import { defineMeta } from '@storybook/addon-svelte-csf'
  import PriorityBadge from '../../src/commons/PriorityBadge.svelte'
  import NarrativeCard from '../../src/commons/NarrativeCard.svelte'
  import Cartouche from '../../src/commons/Cartouche.svelte'
  import StageChip from '../../src/commons/StageChip.svelte'
  import ProgressGauge from '../../src/commons/ProgressGauge.svelte'
  import HealthDot from '../../src/commons/HealthDot.svelte'
  import MilestoneTimeline from '../../src/commons/MilestoneTimeline.svelte'
  import { colorOf, reviewDate, sample, project } from './story-data'
  import { projectGauge } from '@project-review/core/projections'
  import { STAGES } from '@project-review/core/model/project'

  // Reference story: same data, `language = 'en'`. Everything that changes is
  // generated by `t()`; everything that stays in French is ENTERED content —
  // that is the boundary this story makes visible at a glance.
  const language = 'en' as const
  const p4 = project('P-04')

  const { Story } = defineMeta({
    title: 'Reference/English labels',
    parameters: {
      docs: {
        description: {
          component:
            'Global reference: the generated labels switch to English, the entered content (project names, bullets, goal) stays as it is — we never translate what the user wrote.',
        },
      },
    },
  })
</script>

<Story name="English panorama" asChild>
  <div class="panorama" style:--cat={colorOf('P-04')}>
    <div class="row">
      {#each STAGES as stage (stage)}
        <StageChip {stage} {language} />
      {/each}
      <StageChip stage="inProgress" onHold {language} />
    </div>
    <div class="row">
      <HealthDot health="onTrack" {language} shape="chip" />
      <HealthDot health="watch" {language} shape="chip" />
      <HealthDot health="alert" {language} shape="chip" />
      <HealthDot health="critical" {language} shape="chip" />
      <HealthDot {language} shape="chip" />
      <PriorityBadge priority="P1" {language} />
      <PriorityBadge {language} />
      <ProgressGauge gauge={projectGauge(p4)} {language} />
      <ProgressGauge gauge={projectGauge(project('P-05'))} {language} />
    </div>
    <div class="row top">
      <NarrativeCard variant="done" lines={p4.done} {language} />
      <NarrativeCard variant="ongoing" lines={p4.ongoing} {language} />
      <NarrativeCard variant="next" lines={p4.next} {language} />
    </div>
    <MilestoneTimeline milestones={p4.milestones} {reviewDate} {language} />
    <div class="row end">
      <Cartouche identity={sample.settings.identity} review={sample.review} {language} />
    </div>
  </div>
</Story>

<style>
  .panorama {
    width: 1121px;
    display: flex;
    flex-direction: column;
    gap: 27px;
    background: #fff;
  }
  .row {
    display: flex;
    align-items: center;
    gap: 12px;
    flex-wrap: wrap;
  }
  .top {
    align-items: flex-start;
    gap: 44px;
  }
  .end {
    justify-content: flex-end;
  }
</style>
