/**
 * Generate the repository notice table and full installed license texts.
 * Checks installed versions against the reviewed table; --check compares both outputs.
 * License meaning/copyright remain manually reviewed metadata, not an automated guarantee.
 */
import {
  existsSync,
  readFileSync,
  readdirSync,
  realpathSync,
  writeFileSync,
  mkdirSync,
} from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import {
  IMPORTED_CONTENT_NOTICE,
  THIRD_PARTY_NOTICES,
} from '../packages/core/src/data/third-party.ts'

const OUT = 'THIRD-PARTY.md'
const TEXTS = 'dist/THIRD-PARTY-LICENSES.txt'

// Traverse declared dependencies, not a package manager's private store layout.
// pnpm keeps transitive packages beside their owners, not in root node_modules.
const installed = new Map<string, Map<string, string>>()
const pending = ['.', 'app', 'packages/core', 'packages/components', 'packages/infrastructure']
const workspaces = new Set(pending.map((path) => realpathSync(path)))
const visited = new Set<string>()
while (pending.length > 0) {
  const dir = realpathSync(pending.pop()!)
  if (visited.has(dir)) continue
  visited.add(dir)
  const manifestPath = join(dir, 'package.json')
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
  const versions = installed.get(manifest.name) ?? new Map<string, string>()
  versions.set(manifest.version, dir)
  installed.set(manifest.name, versions)
  const require = createRequire(manifestPath)
  for (const name of Object.keys({
    ...manifest.dependencies,
    ...manifest.optionalDependencies,
    ...(workspaces.has(dir) ? manifest.devDependencies : {}),
  })) {
    const found = require.resolve
      .paths(name)
      ?.map((base) => join(base, name))
      .find((candidate) => existsSync(join(candidate, 'package.json')))
    if (found !== undefined) pending.push(found)
  }
}

const packageDir = (pkg: string, version: string): string => {
  const dir = installed.get(pkg)?.get(version)
  if (dir === undefined || installed.get(pkg)?.size !== 1) {
    throw new Error(
      `${pkg}: notice ${version}, installed ${[...(installed.get(pkg)?.keys() ?? [])].join(', ') || 'none'}`,
    )
  }
  return dir
}

/** The installed package's own licence file — whatever it chose to call it. */
const licenseFile = (pkg: string, version: string): string => {
  const dir = packageDir(pkg, version)
  const found = readdirSync(dir).find((entry) => /^(licen[cs]e|copying)(\.|$)/i.test(entry))
  if (found === undefined) throw new Error(`${pkg}: no licence file in ${dir}`)
  return readFileSync(join(dir, found), 'utf8').trimEnd()
}

/** The permission texts, in the order of the table, under the product's own. */
const renderTexts = (): string => {
  const rule = '='.repeat(78)
  const blocks = [
    'THIRD-PARTY LICENSES',
    '',
    'Generated by `pnpm run docs:notices` — texts come from installed packages',
    'or vendored upstream licenses. `THIRD-PARTY.md` in the source',
    'repository, and the About screen of the application itself, name the same',
    'components; this file carries the terms in full.',
    '',
    IMPORTED_CONTENT_NOTICE,
    '',
    rule,
    'project-review',
    rule,
    '',
    readFileSync('LICENSE', 'utf8').trimEnd(),
    '',
  ]
  for (const n of THIRD_PARTY_NOTICES) {
    const text =
      n.pkg !== undefined
        ? licenseFile(n.pkg, n.version)
        : readFileSync(n.licenseFile, 'utf8').trimEnd()
    blocks.push(rule, `${n.name} ${n.version} — ${n.license}`, rule, '', text, '')
  }
  return blocks.join('\n') + '\n'
}

const render = (): string => {
  const lines: string[] = [
    '# Third-party notices',
    '',
    '<!-- Generated by `pnpm run docs:notices` from',
    '     packages/core/src/data/third-party.ts — edit the table, not this file.',
    "     The application's About screen (`#/about`) renders the same data, so a",
    '     deliverable handed on without this repository still carries them. -->',
    '',
    '`project-review` is distributed under the MIT license (see [LICENSE](LICENSE)).',
    'The deliverable embeds the components below. Full terms come from installed',
    'packages or vendored upstream files; labels and copyright are reviewed metadata.',
    '',
    IMPORTED_CONTENT_NOTICE,
    '',
  ]
  for (const n of THIRD_PARTY_NOTICES) {
    lines.push(`## ${n.name} ${n.version}`, '')
    lines.push(`- **License**: ${n.license}`)
    lines.push(`- **Copyright**: ${n.copyright}`)
    lines.push(`- **Used for**: ${n.use}`)
    lines.push(`- **Home**: <${n.url}>`)
    if (n.note !== undefined) lines.push(`- **Note**: ${n.note}`)
    lines.push('')
  }
  return lines.join('\n')
}

const expected = render()
// Reading every licence is itself the check: a package that moved, vanished or
// renamed its licence file throws here, before anything is written.
const expectedTexts = renderTexts()
const carried = THIRD_PARTY_NOTICES.length

const onDisk = (path: string): string => {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return ''
  }
}

if (process.argv.includes('--check')) {
  const stale = (
    [
      [OUT, expected],
      [TEXTS, expectedTexts],
    ] as const
  ).filter(([path, contents]) => onDisk(path) !== contents)
  if (stale.length > 0) {
    console.error(
      `${stale.map(([path]) => path).join(', ')} out of date — run \`pnpm run docs:notices\`.`,
    )
    process.exit(1)
  }
  console.log(
    `${OUT} and ${TEXTS}: up to date (${THIRD_PARTY_NOTICES.length} notices, ${carried} licence texts)`,
  )
} else {
  mkdirSync(dirname(TEXTS), { recursive: true })
  writeFileSync(TEXTS, expectedTexts)
  writeFileSync(OUT, expected)
  console.log(
    `${OUT}: ${THIRD_PARTY_NOTICES.length} notices · ` +
      `${TEXTS}: ${carried} licence texts (${expectedTexts.length} chars)`,
  )
}
