/**
 * Writes `THIRD-PARTY.md` AND `dist/THIRD-PARTY-LICENSES.txt` from the ONE
 * notices table
 * (`packages/core/src/data/third-party.ts`) that the About screen renders.
 * The repository file and the artifact's screen therefore say the same thing
 * by construction rather than by discipline — run `bun run docs:notices` after
 * touching the table, and the check below tells you if you forgot.
 *
 * THE TEXTS THEMSELVES, NOT A TABLE ABOUT THEM. A declarative list says which
 * licence governs what; MIT, BSD and the OFL all require the PERMISSION TEXT
 * to travel with the copy. So the second output concatenates the licence file
 * of every notice — read from the INSTALLED package, never transcribed — and
 * lands beside the deliverable in `dist/`, where whoever receives the artifact
 * receives them too.
 *
 * Reading rather than transcribing is also what keeps the table honest: the
 * file name is matched case-insensitively (`LICENSE`, `LICENSE.md`, `license`
 * and `License` all occur in this tree, and a naive `readFile('LICENSE')`
 * silently misses five packages), and a notice whose package or licence file
 * cannot be found FAILS the run — a version bump that changes a licence stops
 * the build instead of ageing quietly in a table.
 *
 * `--check` writes nothing and exits non-zero when a file on disk has drifted
 * or a licence can no longer be read: that is how CI notices a table edited
 * without a regeneration.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { IMPORTED_CONTENT_NOTICE, THIRD_PARTY_NOTICES } from '../packages/core/src/data/third-party'

const OUT = 'THIRD-PARTY.md'
const TEXTS = 'dist/THIRD-PARTY-LICENSES.txt'

/** The installed package's own licence file — whatever it chose to call it. */
const licenseFile = (pkg: string): string => {
  const dir = join('node_modules', ...pkg.split('/'))
  const found = readdirSync(dir).find((entry) => /^(licen[cs]e|copying)(\.|$)/i.test(entry))
  if (found === undefined) throw new Error(`${pkg}: no licence file in ${dir}`)
  return readFileSync(join(dir, found), 'utf8').trimEnd()
}

/** The permission texts, in the order of the table, under the product's own. */
const renderTexts = (): string => {
  const rule = '='.repeat(78)
  const blocks = [
    'THIRD-PARTY LICENSES',
    '',
    'Generated by `bun run docs:notices` — every text below was read from the',
    'package actually installed for this build. `THIRD-PARTY.md` in the source',
    'repository, and the About screen of the application itself, name the same',
    'components; this file carries the terms in full.',
    '',
    IMPORTED_CONTENT_NOTICE,
    '',
    rule,
    'project-review',
    rule,
    '',
    readFileSync('LICENSE', 'utf8').trimEnd(),
    '',
  ]
  for (const n of THIRD_PARTY_NOTICES) {
    if (n.pkg === undefined) continue
    blocks.push(rule, `${n.name} ${n.version} — ${n.license}`, rule, '', licenseFile(n.pkg), '')
  }
  return blocks.join('\n') + '\n'
}

const render = (): string => {
  const lines: string[] = [
    '# Third-party notices',
    '',
    '<!-- Generated by `bun run docs:notices` from',
    '     packages/core/src/data/third-party.ts — edit the table, not this file.',
    "     The application's About screen (`#/about`) renders the same data, so a",
    '     deliverable handed on without this repository still carries them. -->',
    '',
    '`project-review` is distributed under the MIT license (see [LICENSE](LICENSE)).',
    'The single-file deliverable embeds the components below; each license was read',
    'from the package actually installed, and each copyright line is quoted verbatim.',
    '',
    IMPORTED_CONTENT_NOTICE,
    '',
  ]
  for (const n of THIRD_PARTY_NOTICES) {
    lines.push(`## ${n.name} ${n.version}`, '')
    lines.push(`- **License**: ${n.license}`)
    lines.push(`- **Copyright**: ${n.copyright}`)
    lines.push(`- **Used for**: ${n.use}`)
    lines.push(`- **Home**: <${n.url}>`)
    if (n.note !== undefined) lines.push(`- **Note**: ${n.note}`)
    lines.push('')
  }
  return lines.join('\n')
}

const expected = render()
// Reading every licence is itself the check: a package that moved, vanished or
// renamed its licence file throws here, before anything is written.
const expectedTexts = renderTexts()
const carried = THIRD_PARTY_NOTICES.filter((n) => n.pkg !== undefined).length

const onDisk = (path: string): string => {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return ''
  }
}

if (process.argv.includes('--check')) {
  if (onDisk(OUT) !== expected) {
    console.error(`${OUT} is out of date — run \`bun run docs:notices\`.`)
    process.exit(1)
  }
  console.log(
    `${OUT}: up to date (${THIRD_PARTY_NOTICES.length} notices, ${carried} licence texts read)`,
  )
} else {
  mkdirSync(dirname(TEXTS), { recursive: true })
  writeFileSync(TEXTS, expectedTexts)
  writeFileSync(OUT, expected)
  console.log(
    `${OUT}: ${THIRD_PARTY_NOTICES.length} notices · ` +
      `${TEXTS}: ${carried} licence texts (${expectedTexts.length} chars)`,
  )
}
