/**
 * Writes `THIRD-PARTY.md` from the ONE notices table
 * (`packages/core/src/data/third-party.ts`) that the About screen renders.
 * The repository file and the artifact's screen therefore say the same thing
 * by construction rather than by discipline — run `bun run docs:notices` after
 * touching the table, and the check below tells you if you forgot.
 *
 * `--check` writes nothing and exits non-zero when the file on disk has
 * drifted: that is how CI notices a table edited without a regeneration.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { IMPORTED_CONTENT_NOTICE, THIRD_PARTY_NOTICES } from '../packages/core/src/data/third-party'

const OUT = 'THIRD-PARTY.md'

const render = (): string => {
  const lines: string[] = [
    '# Third-party notices',
    '',
    '<!-- Generated by `bun run docs:notices` from',
    '     packages/core/src/data/third-party.ts — edit the table, not this file.',
    "     The application's About screen (`#/about`) renders the same data, so a",
    '     deliverable handed on without this repository still carries them. -->',
    '',
    '`project-review` is distributed under the MIT license (see [LICENSE](LICENSE)).',
    'The single-file deliverable embeds the components below; each license was read',
    'from the package actually installed, and each copyright line is quoted verbatim.',
    '',
    IMPORTED_CONTENT_NOTICE,
    '',
  ]
  for (const n of THIRD_PARTY_NOTICES) {
    lines.push(`## ${n.name} ${n.version}`, '')
    lines.push(`- **License**: ${n.license}`)
    lines.push(`- **Copyright**: ${n.copyright}`)
    lines.push(`- **Used for**: ${n.use}`)
    lines.push(`- **Home**: <${n.url}>`)
    if (n.note !== undefined) lines.push(`- **Note**: ${n.note}`)
    lines.push('')
  }
  return lines.join('\n')
}

const expected = render()

if (process.argv.includes('--check')) {
  const actual = (() => {
    try {
      return readFileSync(OUT, 'utf8')
    } catch {
      return ''
    }
  })()
  if (actual !== expected) {
    console.error(`${OUT} is out of date — run \`bun run docs:notices\`.`)
    process.exit(1)
  }
  console.log(`${OUT}: up to date (${THIRD_PARTY_NOTICES.length} notices)`)
} else {
  writeFileSync(OUT, expected)
  console.log(`${OUT}: ${THIRD_PARTY_NOTICES.length} notices`)
}
